### ISSUE TITLE
Teleport not working

### ISSUE THREAD

**Issue by IceColdx** [XxFri3ndlyxX/Teleport#1]
I have this installed with your fivemipl and esx_illegal_drugs. It didn't work so i set the marker visibility to true but the markers don't seem to show up either. When starting the server it's starting resource Teleport without errors.

In config it looks like this: 
start esx_burglary
start burglary
start esx_illegal_drugs
start fivem-ipl
start Teleport

**Comment by IceColdx** [comment]
Wasn't able to fix yours so i took another teleport script and edited it to work with your illegal drugs script

**Comment by XxFri3ndlyxX** [comment]
There is nothing to fix. This teleport works fine. You messed up somewhere. Look your log in fivem application data for errors.
